version: '3.4'

services:
  mysql:
    image: mysql:8.0.39-debian
    environment:
      MYSQL_DATABASE: CS502052  
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"  
    volumes:
      - mysql_data:/var/lib/mysql 

volumes:
  mysql_data:
