spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/CS502052"
    username: "root"
    password:
  jpa:
    ddl-auto: "update"
    properties:
      dialect: "org.hibernate.dialect.MySQLDialect"