server:
  port: 8081
  servlet:
    session:
      timeout: 24h
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/CS502052"
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: phantipo2333@gmail.com
    password: jlms ogfu usuu fnrc
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.protocols: TLSv1.2

jwt:
  signerKey: "3yrdhh+tGeku/H0Lscu6Dgfq4k+m6a5GEgP5c8SEZeq4GL7evfYjhraygtfxKHU+"
